# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun May 20 17:52:48 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1125, 773)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.scatter_frame_top = QtGui.QFrame(self.page)
        self.scatter_frame_top.setMaximumSize(QtCore.QSize(16777215, 43))
        self.scatter_frame_top.setFrameShape(QtGui.QFrame.NoFrame)
        self.scatter_frame_top.setFrameShadow(QtGui.QFrame.Plain)
        self.scatter_frame_top.setObjectName(_fromUtf8("scatter_frame_top"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scatter_frame_top)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.comboBox_feature_x = QtGui.QComboBox(self.scatter_frame_top)
        self.comboBox_feature_x.setObjectName(_fromUtf8("comboBox_feature_x"))
        self.horizontalLayout_4.addWidget(self.comboBox_feature_x)
        self.comboBox_feature_x_chan = QtGui.QComboBox(self.scatter_frame_top)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_feature_x_chan.sizePolicy().hasHeightForWidth())
        self.comboBox_feature_x_chan.setSizePolicy(sizePolicy)
        self.comboBox_feature_x_chan.setMinimumSize(QtCore.QSize(31, 22))
        self.comboBox_feature_x_chan.setMaximumSize(QtCore.QSize(31, 22))
        self.comboBox_feature_x_chan.setObjectName(_fromUtf8("comboBox_feature_x_chan"))
        self.comboBox_feature_x_chan.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_feature_x_chan)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.comboBox_feature_y = QtGui.QComboBox(self.scatter_frame_top)
        self.comboBox_feature_y.setObjectName(_fromUtf8("comboBox_feature_y"))
        self.horizontalLayout_5.addWidget(self.comboBox_feature_y)
        self.comboBox_feature_y_chan = QtGui.QComboBox(self.scatter_frame_top)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_feature_y_chan.sizePolicy().hasHeightForWidth())
        self.comboBox_feature_y_chan.setSizePolicy(sizePolicy)
        self.comboBox_feature_y_chan.setMinimumSize(QtCore.QSize(31, 22))
        self.comboBox_feature_y_chan.setMaximumSize(QtCore.QSize(31, 22))
        self.comboBox_feature_y_chan.setObjectName(_fromUtf8("comboBox_feature_y_chan"))
        self.comboBox_feature_y_chan.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBox_feature_y_chan)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_previous_projection = QtGui.QPushButton(self.scatter_frame_top)
        self.pushButton_previous_projection.setMinimumSize(QtCore.QSize(31, 23))
        self.pushButton_previous_projection.setMaximumSize(QtCore.QSize(31, 23))
        self.pushButton_previous_projection.setObjectName(_fromUtf8("pushButton_previous_projection"))
        self.horizontalLayout_6.addWidget(self.pushButton_previous_projection)
        self.pushButton_next_projection = QtGui.QPushButton(self.scatter_frame_top)
        self.pushButton_next_projection.setMinimumSize(QtCore.QSize(31, 23))
        self.pushButton_next_projection.setMaximumSize(QtCore.QSize(31, 23))
        self.pushButton_next_projection.setObjectName(_fromUtf8("pushButton_next_projection"))
        self.horizontalLayout_6.addWidget(self.pushButton_next_projection)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.checkBox_refractory = QtGui.QCheckBox(self.scatter_frame_top)
        self.checkBox_refractory.setChecked(True)
        self.checkBox_refractory.setObjectName(_fromUtf8("checkBox_refractory"))
        self.horizontalLayout_2.addWidget(self.checkBox_refractory)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.radioButton_scatter = QtGui.QRadioButton(self.scatter_frame_top)
        self.radioButton_scatter.setMinimumSize(QtCore.QSize(58, 17))
        self.radioButton_scatter.setMaximumSize(QtCore.QSize(58, 17))
        self.radioButton_scatter.setChecked(True)
        self.radioButton_scatter.setObjectName(_fromUtf8("radioButton_scatter"))
        self.buttonGroup_scatter_plot_type = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_scatter_plot_type.setObjectName(_fromUtf8("buttonGroup_scatter_plot_type"))
        self.buttonGroup_scatter_plot_type.addButton(self.radioButton_scatter)
        self.horizontalLayout_8.addWidget(self.radioButton_scatter)
        self.radioButton_density = QtGui.QRadioButton(self.scatter_frame_top)
        self.radioButton_density.setMinimumSize(QtCore.QSize(59, 17))
        self.radioButton_density.setMaximumSize(QtCore.QSize(59, 17))
        self.radioButton_density.setObjectName(_fromUtf8("radioButton_density"))
        self.buttonGroup_scatter_plot_type.addButton(self.radioButton_density)
        self.horizontalLayout_8.addWidget(self.radioButton_density)
        self.radioButton_log_density = QtGui.QRadioButton(self.scatter_frame_top)
        self.radioButton_log_density.setMinimumSize(QtCore.QSize(79, 17))
        self.radioButton_log_density.setMaximumSize(QtCore.QSize(79, 17))
        self.radioButton_log_density.setChecked(False)
        self.radioButton_log_density.setObjectName(_fromUtf8("radioButton_log_density"))
        self.buttonGroup_scatter_plot_type.addButton(self.radioButton_log_density)
        self.horizontalLayout_8.addWidget(self.radioButton_log_density)
        self.checkBox_ellipse = QtGui.QCheckBox(self.scatter_frame_top)
        self.checkBox_ellipse.setChecked(True)
        self.checkBox_ellipse.setObjectName(_fromUtf8("checkBox_ellipse"))
        self.horizontalLayout_8.addWidget(self.checkBox_ellipse)
        self.label_3 = QtGui.QLabel(self.scatter_frame_top)
        self.label_3.setMinimumSize(QtCore.QSize(59, 20))
        self.label_3.setMaximumSize(QtCore.QSize(59, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.spinBox_markerSize = QtGui.QSpinBox(self.scatter_frame_top)
        self.spinBox_markerSize.setMinimumSize(QtCore.QSize(42, 20))
        self.spinBox_markerSize.setMaximumSize(QtCore.QSize(42, 20))
        self.spinBox_markerSize.setMinimum(1)
        self.spinBox_markerSize.setMaximum(25)
        self.spinBox_markerSize.setSingleStep(1)
        self.spinBox_markerSize.setProperty("value", 1)
        self.spinBox_markerSize.setObjectName(_fromUtf8("spinBox_markerSize"))
        self.horizontalLayout_8.addWidget(self.spinBox_markerSize)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.scatter_frame_top)
        self.splitter = QtGui.QSplitter(self.page)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.mplwidget_projection = MatplotlibWidget(self.frame_3)
        self.mplwidget_projection.setAutoFillBackground(True)
        self.mplwidget_projection.setObjectName(_fromUtf8("mplwidget_projection"))
        self.verticalLayout_3.addWidget(self.mplwidget_projection)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setMinimumSize(QtCore.QSize(160, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton_addLimit = QtGui.QPushButton(self.frame_2)
        self.pushButton_addLimit.setEnabled(True)
        self.pushButton_addLimit.setMinimumSize(QtCore.QSize(60, 23))
        self.pushButton_addLimit.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_addLimit.setObjectName(_fromUtf8("pushButton_addLimit"))
        self.horizontalLayout_9.addWidget(self.pushButton_addLimit)
        self.pushButton_deleteLimit = QtGui.QPushButton(self.frame_2)
        self.pushButton_deleteLimit.setEnabled(True)
        self.pushButton_deleteLimit.setMinimumSize(QtCore.QSize(60, 23))
        self.pushButton_deleteLimit.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_deleteLimit.setObjectName(_fromUtf8("pushButton_deleteLimit"))
        self.horizontalLayout_9.addWidget(self.pushButton_deleteLimit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.pushButton_hide_all = QtGui.QPushButton(self.frame_2)
        self.pushButton_hide_all.setObjectName(_fromUtf8("pushButton_hide_all"))
        self.horizontalLayout_16.addWidget(self.pushButton_hide_all)
        self.pushButton_show_all = QtGui.QPushButton(self.frame_2)
        self.pushButton_show_all.setObjectName(_fromUtf8("pushButton_show_all"))
        self.horizontalLayout_16.addWidget(self.pushButton_show_all)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.scrollArea_cluster_list = QtGui.QScrollArea(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_cluster_list.sizePolicy().hasHeightForWidth())
        self.scrollArea_cluster_list.setSizePolicy(sizePolicy)
        self.scrollArea_cluster_list.setMinimumSize(QtCore.QSize(0, 431))
        self.scrollArea_cluster_list.setMaximumSize(QtCore.QSize(160, 16777215))
        self.scrollArea_cluster_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_cluster_list.setWidgetResizable(True)
        self.scrollArea_cluster_list.setObjectName(_fromUtf8("scrollArea_cluster_list"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 121, 429))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea_cluster_list.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea_cluster_list)
        self.frame_clusterbuttons = QtGui.QFrame(self.frame_2)
        self.frame_clusterbuttons.setMaximumSize(QtCore.QSize(160, 159))
        self.frame_clusterbuttons.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_clusterbuttons.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_clusterbuttons.setLineWidth(1)
        self.frame_clusterbuttons.setObjectName(_fromUtf8("frame_clusterbuttons"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_clusterbuttons)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_add_cluster = QtGui.QPushButton(self.frame_clusterbuttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_cluster.sizePolicy().hasHeightForWidth())
        self.pushButton_add_cluster.setSizePolicy(sizePolicy)
        self.pushButton_add_cluster.setMinimumSize(QtCore.QSize(81, 23))
        self.pushButton_add_cluster.setObjectName(_fromUtf8("pushButton_add_cluster"))
        self.verticalLayout.addWidget(self.pushButton_add_cluster)
        self.pushButton_delete_cluster = QtGui.QPushButton(self.frame_clusterbuttons)
        self.pushButton_delete_cluster.setMinimumSize(QtCore.QSize(81, 23))
        self.pushButton_delete_cluster.setObjectName(_fromUtf8("pushButton_delete_cluster"))
        self.verticalLayout.addWidget(self.pushButton_delete_cluster)
        self.pushButton_copy_cluster = QtGui.QPushButton(self.frame_clusterbuttons)
        self.pushButton_copy_cluster.setObjectName(_fromUtf8("pushButton_copy_cluster"))
        self.verticalLayout.addWidget(self.pushButton_copy_cluster)
        self.pushButton_wavecutter_start = QtGui.QPushButton(self.frame_clusterbuttons)
        self.pushButton_wavecutter_start.setObjectName(_fromUtf8("pushButton_wavecutter_start"))
        self.verticalLayout.addWidget(self.pushButton_wavecutter_start)
        self.verticalLayout_4.addWidget(self.frame_clusterbuttons)
        self.verticalLayout_5.addWidget(self.splitter)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.stackedWidget_trimmer = QtGui.QStackedWidget(self.page_2)
        self.stackedWidget_trimmer.setObjectName(_fromUtf8("stackedWidget_trimmer"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.mplwidget_wavecutter = MatplotlibWidget(self.page_3)
        self.mplwidget_wavecutter.setAutoFillBackground(True)
        self.mplwidget_wavecutter.setObjectName(_fromUtf8("mplwidget_wavecutter"))
        self.verticalLayout_7.addWidget(self.mplwidget_wavecutter)
        self.frame = QtGui.QFrame(self.page_3)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.pushButton_wavecutter_redraw = QtGui.QPushButton(self.frame)
        self.pushButton_wavecutter_redraw.setObjectName(_fromUtf8("pushButton_wavecutter_redraw"))
        self.horizontalLayout_20.addWidget(self.pushButton_wavecutter_redraw)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_17.addWidget(self.label_2)
        self.spinBox_wavecutter_channel = QtGui.QSpinBox(self.frame)
        self.spinBox_wavecutter_channel.setMinimum(1)
        self.spinBox_wavecutter_channel.setMaximum(4)
        self.spinBox_wavecutter_channel.setObjectName(_fromUtf8("spinBox_wavecutter_channel"))
        self.horizontalLayout_17.addWidget(self.spinBox_wavecutter_channel)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_17)
        self.checkBox_wavecutter_refractory = QtGui.QCheckBox(self.frame)
        self.checkBox_wavecutter_refractory.setObjectName(_fromUtf8("checkBox_wavecutter_refractory"))
        self.horizontalLayout_20.addWidget(self.checkBox_wavecutter_refractory)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_18.addWidget(self.label_11)
        self.lineEdit_wavecutter_count = QtGui.QLineEdit(self.frame)
        self.lineEdit_wavecutter_count.setMaximumSize(QtCore.QSize(51, 16777215))
        self.lineEdit_wavecutter_count.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_wavecutter_count.setObjectName(_fromUtf8("lineEdit_wavecutter_count"))
        self.horizontalLayout_18.addWidget(self.lineEdit_wavecutter_count)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_18)
        spacerItem1 = QtGui.QSpacerItem(11, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.pushButton_wavecutter_add_limit = QtGui.QPushButton(self.frame)
        self.pushButton_wavecutter_add_limit.setObjectName(_fromUtf8("pushButton_wavecutter_add_limit"))
        self.horizontalLayout_19.addWidget(self.pushButton_wavecutter_add_limit)
        self.pushButton_wavecutter_remove_limit = QtGui.QPushButton(self.frame)
        self.pushButton_wavecutter_remove_limit.setObjectName(_fromUtf8("pushButton_wavecutter_remove_limit"))
        self.horizontalLayout_19.addWidget(self.pushButton_wavecutter_remove_limit)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget_trimmer.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.mplwidget_outliers = MatplotlibWidget(self.page_4)
        self.mplwidget_outliers.setGeometry(QtCore.QRect(20, 30, 731, 561))
        self.mplwidget_outliers.setObjectName(_fromUtf8("mplwidget_outliers"))
        self.stackedWidget_trimmer.addWidget(self.page_4)
        self.verticalLayout_8.addWidget(self.stackedWidget_trimmer)
        self.frame_5 = QtGui.QFrame(self.page_2)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.radioButton_wavecutter = QtGui.QRadioButton(self.frame_5)
        self.radioButton_wavecutter.setChecked(True)
        self.radioButton_wavecutter.setObjectName(_fromUtf8("radioButton_wavecutter"))
        self.buttonGroup_trimmer = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_trimmer.setObjectName(_fromUtf8("buttonGroup_trimmer"))
        self.buttonGroup_trimmer.addButton(self.radioButton_wavecutter)
        self.horizontalLayout_22.addWidget(self.radioButton_wavecutter)
        self.radioButton_outlier = QtGui.QRadioButton(self.frame_5)
        self.radioButton_outlier.setObjectName(_fromUtf8("radioButton_outlier"))
        self.buttonGroup_trimmer.addButton(self.radioButton_outlier)
        self.horizontalLayout_22.addWidget(self.radioButton_outlier)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_22)
        spacerItem2 = QtGui.QSpacerItem(414, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem2)
        self.pushButton_wavecutter_done = QtGui.QPushButton(self.frame_5)
        self.pushButton_wavecutter_done.setObjectName(_fromUtf8("pushButton_wavecutter_done"))
        self.horizontalLayout_23.addWidget(self.pushButton_wavecutter_done)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_21.addWidget(self.stackedWidget)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(285, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_4 = QtGui.QFrame(self.widget)
        self.frame_4.setMaximumSize(QtCore.QSize(267, 16777215))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.frame_4)
        self.splitter_2.setMinimumSize(QtCore.QSize(235, 0))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pushButton = QtGui.QPushButton(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_save = QtGui.QPushButton(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_save.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.pushButton_import = QtGui.QPushButton(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_import.sizePolicy().hasHeightForWidth())
        self.pushButton_import.setSizePolicy(sizePolicy)
        self.pushButton_import.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_import.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_import.setObjectName(_fromUtf8("pushButton_import"))
        self.horizontalLayout_7.addWidget(self.splitter_2)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.frame_details_display = QtGui.QFrame(self.widget)
        self.frame_details_display.setMinimumSize(QtCore.QSize(267, 0))
        self.frame_details_display.setMaximumSize(QtCore.QSize(267, 16777215))
        self.frame_details_display.setFrameShape(QtGui.QFrame.Box)
        self.frame_details_display.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_details_display.setObjectName(_fromUtf8("frame_details_display"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_details_display)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mplwidget_isi = MatplotlibWidget(self.frame_details_display)
        self.mplwidget_isi.setMinimumSize(QtCore.QSize(247, 150))
        self.mplwidget_isi.setMaximumSize(QtCore.QSize(289, 175))
        self.mplwidget_isi.setObjectName(_fromUtf8("mplwidget_isi"))
        self.verticalLayout_2.addWidget(self.mplwidget_isi)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.label_mean_rate = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_mean_rate.setFont(font)
        self.label_mean_rate.setObjectName(_fromUtf8("label_mean_rate"))
        self.horizontalLayout.addWidget(self.label_mean_rate)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.label_csi = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_csi.setFont(font)
        self.label_csi.setObjectName(_fromUtf8("label_csi"))
        self.horizontalLayout_3.addWidget(self.label_csi)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.label_refr_count = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_refr_count.setFont(font)
        self.label_refr_count.setObjectName(_fromUtf8("label_refr_count"))
        self.horizontalLayout_10.addWidget(self.label_refr_count)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.label_isolation = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_isolation.setFont(font)
        self.label_isolation.setObjectName(_fromUtf8("label_isolation"))
        self.horizontalLayout_11.addWidget(self.label_isolation)
        self.gridLayout.addLayout(self.horizontalLayout_11, 3, 1, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.label_spike_count = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_spike_count.setFont(font)
        self.label_spike_count.setObjectName(_fromUtf8("label_spike_count"))
        self.horizontalLayout_12.addWidget(self.label_spike_count)
        self.gridLayout.addLayout(self.horizontalLayout_12, 0, 4, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem8)
        self.label_burst = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_burst.setFont(font)
        self.label_burst.setObjectName(_fromUtf8("label_burst"))
        self.horizontalLayout_13.addWidget(self.label_burst)
        self.gridLayout.addLayout(self.horizontalLayout_13, 1, 4, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.label_refr_fp = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_refr_fp.setFont(font)
        self.label_refr_fp.setObjectName(_fromUtf8("label_refr_fp"))
        self.horizontalLayout_14.addWidget(self.label_refr_fp)
        self.gridLayout.addLayout(self.horizontalLayout_14, 2, 4, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 0, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 2, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 2, 2, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 3, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.label_refr_frac = QtGui.QLabel(self.frame_details_display)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_refr_frac.setFont(font)
        self.label_refr_frac.setObjectName(_fromUtf8("label_refr_frac"))
        self.horizontalLayout_15.addWidget(self.label_refr_frac)
        self.gridLayout.addLayout(self.horizontalLayout_15, 3, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.mplwidget_waveform = MatplotlibWidget(self.frame_details_display)
        self.mplwidget_waveform.setMaximumSize(QtCore.QSize(291, 16777215))
        self.mplwidget_waveform.setObjectName(_fromUtf8("mplwidget_waveform"))
        self.verticalLayout_2.addWidget(self.mplwidget_waveform)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.mplwidget_drift = MatplotlibWidget(self.frame_details_display)
        self.mplwidget_drift.setObjectName(_fromUtf8("mplwidget_drift"))
        self.verticalLayout_2.addWidget(self.mplwidget_drift)
        self.verticalLayout_6.addWidget(self.frame_details_display)
        self.horizontalLayout_21.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_trimmer.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_feature_x_chan.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_feature_y_chan.setItemText(0, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_previous_projection.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_projection.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_refractory.setText(QtGui.QApplication.translate("MainWindow", "Refractory", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_scatter.setText(QtGui.QApplication.translate("MainWindow", "Scatter", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_density.setText(QtGui.QApplication.translate("MainWindow", "Density", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_log_density.setText(QtGui.QApplication.translate("MainWindow", "Log D", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ellipse.setText(QtGui.QApplication.translate("MainWindow", "Elliptical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Marker Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_addLimit.setText(QtGui.QApplication.translate("MainWindow", "Add Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_deleteLimit.setText(QtGui.QApplication.translate("MainWindow", "Delete Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hide_all.setText(QtGui.QApplication.translate("MainWindow", "Hide All", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_show_all.setText(QtGui.QApplication.translate("MainWindow", "Show All", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_cluster.setText(QtGui.QApplication.translate("MainWindow", "Add Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete_cluster.setText(QtGui.QApplication.translate("MainWindow", "Delete Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_copy_cluster.setText(QtGui.QApplication.translate("MainWindow", "Copy Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_wavecutter_start.setText(QtGui.QApplication.translate("MainWindow", "Waveform Cutter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_wavecutter_redraw.setText(QtGui.QApplication.translate("MainWindow", "Redraw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Channel:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_wavecutter_refractory.setText(QtGui.QApplication.translate("MainWindow", "Refractory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Number of Waveforms:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_wavecutter_count.setInputMask(QtGui.QApplication.translate("MainWindow", "0000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_wavecutter_count.setText(QtGui.QApplication.translate("MainWindow", "500", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_wavecutter_add_limit.setText(QtGui.QApplication.translate("MainWindow", "Add Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_wavecutter_remove_limit.setText(QtGui.QApplication.translate("MainWindow", "Remove Limits", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_wavecutter.setText(QtGui.QApplication.translate("MainWindow", "Waveform Cutter", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_outlier.setText(QtGui.QApplication.translate("MainWindow", "Outlier Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_wavecutter_done.setText(QtGui.QApplication.translate("MainWindow", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load NTT", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_import.setText(QtGui.QApplication.translate("MainWindow", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Spikes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "CSI:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Burst Index:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Refr. Viol", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Isolation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Refr. False Pos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Firing Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mean_rate.setText(QtGui.QApplication.translate("MainWindow", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_csi.setText(QtGui.QApplication.translate("MainWindow", " a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_refr_count.setText(QtGui.QApplication.translate("MainWindow", " a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_isolation.setText(QtGui.QApplication.translate("MainWindow", " a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_spike_count.setText(QtGui.QApplication.translate("MainWindow", " a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_burst.setText(QtGui.QApplication.translate("MainWindow", " a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_refr_fp.setText(QtGui.QApplication.translate("MainWindow", " a", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Refr. Fraction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_refr_frac.setText(QtGui.QApplication.translate("MainWindow", " a", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
