# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyclust_main_layout.ui'
#
# Created: Fri Mar 30 18:04:40 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1224, 799)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_clusterbuttons = QtGui.QFrame(self.centralwidget)
        self.frame_clusterbuttons.setGeometry(QtCore.QRect(810, 470, 136, 159))
        self.frame_clusterbuttons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_clusterbuttons.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_clusterbuttons.setLineWidth(1)
        self.frame_clusterbuttons.setObjectName(_fromUtf8("frame_clusterbuttons"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_clusterbuttons)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_add_cluster = QtGui.QPushButton(self.frame_clusterbuttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add_cluster.sizePolicy().hasHeightForWidth())
        self.pushButton_add_cluster.setSizePolicy(sizePolicy)
        self.pushButton_add_cluster.setMinimumSize(QtCore.QSize(116, 23))
        self.pushButton_add_cluster.setText(QtGui.QApplication.translate("MainWindow", "Add Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_cluster.setObjectName(_fromUtf8("pushButton_add_cluster"))
        self.verticalLayout.addWidget(self.pushButton_add_cluster)
        self.pushButton_delete_cluster = QtGui.QPushButton(self.frame_clusterbuttons)
        self.pushButton_delete_cluster.setMinimumSize(QtCore.QSize(116, 23))
        self.pushButton_delete_cluster.setText(QtGui.QApplication.translate("MainWindow", "Delete Current Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete_cluster.setObjectName(_fromUtf8("pushButton_delete_cluster"))
        self.verticalLayout.addWidget(self.pushButton_delete_cluster)
        self.pushButton_2 = QtGui.QPushButton(self.frame_clusterbuttons)
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.frame_clusterbuttons)
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtGui.QPushButton(self.frame_clusterbuttons)
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.scrollArea_cluster_list = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea_cluster_list.setGeometry(QtCore.QRect(801, 51, 151, 391))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_cluster_list.sizePolicy().hasHeightForWidth())
        self.scrollArea_cluster_list.setSizePolicy(sizePolicy)
        self.scrollArea_cluster_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_cluster_list.setWidgetResizable(True)
        self.scrollArea_cluster_list.setObjectName(_fromUtf8("scrollArea_cluster_list"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 132, 389))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea_cluster_list.setWidget(self.scrollAreaWidgetContents)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 941, 25))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load NTT", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_quit = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_quit.sizePolicy().hasHeightForWidth())
        self.pushButton_quit.setSizePolicy(sizePolicy)
        self.pushButton_quit.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_quit.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_quit.setObjectName(_fromUtf8("pushButton_quit"))
        self.horizontalLayout_2.addWidget(self.pushButton_quit)
        self.mplwidget_projection = MatplotlibWidget(self.centralwidget)
        self.mplwidget_projection.setGeometry(QtCore.QRect(11, 45, 411, 511))
        self.mplwidget_projection.setAutoFillBackground(True)
        self.mplwidget_projection.setObjectName(_fromUtf8("mplwidget_projection"))
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(10, 590, 411, 27))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.comboBox_feature_x = QtGui.QComboBox(self.widget1)
        self.comboBox_feature_x.setObjectName(_fromUtf8("comboBox_feature_x"))
        self.horizontalLayout_4.addWidget(self.comboBox_feature_x)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.comboBox_feature_x_chan = QtGui.QComboBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_feature_x_chan.sizePolicy().hasHeightForWidth())
        self.comboBox_feature_x_chan.setSizePolicy(sizePolicy)
        self.comboBox_feature_x_chan.setMinimumSize(QtCore.QSize(31, 22))
        self.comboBox_feature_x_chan.setMaximumSize(QtCore.QSize(31, 22))
        self.comboBox_feature_x_chan.setObjectName(_fromUtf8("comboBox_feature_x_chan"))
        self.comboBox_feature_x_chan.addItem(_fromUtf8(""))
        self.comboBox_feature_x_chan.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_4.addWidget(self.comboBox_feature_x_chan)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.comboBox_feature_y = QtGui.QComboBox(self.widget1)
        self.comboBox_feature_y.setObjectName(_fromUtf8("comboBox_feature_y"))
        self.horizontalLayout_5.addWidget(self.comboBox_feature_y)
        self.comboBox_feature_y_chan = QtGui.QComboBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_feature_y_chan.sizePolicy().hasHeightForWidth())
        self.comboBox_feature_y_chan.setSizePolicy(sizePolicy)
        self.comboBox_feature_y_chan.setMinimumSize(QtCore.QSize(31, 22))
        self.comboBox_feature_y_chan.setMaximumSize(QtCore.QSize(31, 22))
        self.comboBox_feature_y_chan.setObjectName(_fromUtf8("comboBox_feature_y_chan"))
        self.comboBox_feature_y_chan.addItem(_fromUtf8(""))
        self.comboBox_feature_y_chan.setItemText(0, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout_5.addWidget(self.comboBox_feature_y_chan)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_previous_projection = QtGui.QPushButton(self.widget1)
        self.pushButton_previous_projection.setMinimumSize(QtCore.QSize(31, 23))
        self.pushButton_previous_projection.setMaximumSize(QtCore.QSize(31, 23))
        self.pushButton_previous_projection.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_previous_projection.setObjectName(_fromUtf8("pushButton_previous_projection"))
        self.horizontalLayout_6.addWidget(self.pushButton_previous_projection)
        self.pushButton_next_projection = QtGui.QPushButton(self.widget1)
        self.pushButton_next_projection.setMinimumSize(QtCore.QSize(31, 23))
        self.pushButton_next_projection.setMaximumSize(QtCore.QSize(31, 23))
        self.pushButton_next_projection.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_next_projection.setObjectName(_fromUtf8("pushButton_next_projection"))
        self.horizontalLayout_6.addWidget(self.pushButton_next_projection)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.widget2 = QtGui.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 620, 411, 22))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtGui.QLabel(self.widget2)
        self.label_2.setMinimumSize(QtCore.QSize(46, 20))
        self.label_2.setMaximumSize(QtCore.QSize(46, 20))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "PlotStyle:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.radioButton_scatter = QtGui.QRadioButton(self.widget2)
        self.radioButton_scatter.setMinimumSize(QtCore.QSize(58, 17))
        self.radioButton_scatter.setMaximumSize(QtCore.QSize(58, 17))
        self.radioButton_scatter.setText(QtGui.QApplication.translate("MainWindow", "Scatter", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_scatter.setChecked(True)
        self.radioButton_scatter.setObjectName(_fromUtf8("radioButton_scatter"))
        self.buttonGroup_scatter_plot_type = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_scatter_plot_type.setObjectName(_fromUtf8("buttonGroup_scatter_plot_type"))
        self.buttonGroup_scatter_plot_type.addButton(self.radioButton_scatter)
        self.horizontalLayout_8.addWidget(self.radioButton_scatter)
        self.radioButton_density = QtGui.QRadioButton(self.widget2)
        self.radioButton_density.setMinimumSize(QtCore.QSize(59, 17))
        self.radioButton_density.setMaximumSize(QtCore.QSize(59, 17))
        self.radioButton_density.setText(QtGui.QApplication.translate("MainWindow", "Density", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_density.setObjectName(_fromUtf8("radioButton_density"))
        self.buttonGroup_scatter_plot_type.addButton(self.radioButton_density)
        self.horizontalLayout_8.addWidget(self.radioButton_density)
        self.radioButton_log_density = QtGui.QRadioButton(self.widget2)
        self.radioButton_log_density.setMinimumSize(QtCore.QSize(79, 17))
        self.radioButton_log_density.setMaximumSize(QtCore.QSize(79, 17))
        self.radioButton_log_density.setText(QtGui.QApplication.translate("MainWindow", "Log Density", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_log_density.setChecked(False)
        self.radioButton_log_density.setObjectName(_fromUtf8("radioButton_log_density"))
        self.buttonGroup_scatter_plot_type.addButton(self.radioButton_log_density)
        self.horizontalLayout_8.addWidget(self.radioButton_log_density)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.label_3 = QtGui.QLabel(self.widget2)
        self.label_3.setMinimumSize(QtCore.QSize(59, 20))
        self.label_3.setMaximumSize(QtCore.QSize(59, 20))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Marker Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.spinBox_markerSize = QtGui.QSpinBox(self.widget2)
        self.spinBox_markerSize.setMinimumSize(QtCore.QSize(42, 20))
        self.spinBox_markerSize.setMaximumSize(QtCore.QSize(42, 20))
        self.spinBox_markerSize.setMinimum(1)
        self.spinBox_markerSize.setSingleStep(5)
        self.spinBox_markerSize.setObjectName(_fromUtf8("spinBox_markerSize"))
        self.horizontalLayout_8.addWidget(self.spinBox_markerSize)
        self.widget3 = QtGui.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(10, 560, 411, 25))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton_resetzoom = QtGui.QPushButton(self.widget3)
        self.pushButton_resetzoom.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_resetzoom.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_resetzoom.setText(QtGui.QApplication.translate("MainWindow", "Reset Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_resetzoom.setObjectName(_fromUtf8("pushButton_resetzoom"))
        self.horizontalLayout_9.addWidget(self.pushButton_resetzoom)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.pushButton_addLimit = QtGui.QPushButton(self.widget3)
        self.pushButton_addLimit.setMinimumSize(QtCore.QSize(75, 23))
        self.pushButton_addLimit.setMaximumSize(QtCore.QSize(75, 23))
        self.pushButton_addLimit.setText(QtGui.QApplication.translate("MainWindow", "Add Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_addLimit.setObjectName(_fromUtf8("pushButton_addLimit"))
        self.horizontalLayout_9.addWidget(self.pushButton_addLimit)
        self.splitter_isi_waveform = QtGui.QSplitter(self.centralwidget)
        self.splitter_isi_waveform.setGeometry(QtCore.QRect(429, 45, 365, 595))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_isi_waveform.sizePolicy().hasHeightForWidth())
        self.splitter_isi_waveform.setSizePolicy(sizePolicy)
        self.splitter_isi_waveform.setOrientation(QtCore.Qt.Vertical)
        self.splitter_isi_waveform.setObjectName(_fromUtf8("splitter_isi_waveform"))
        self.mplwidget_isi = MatplotlibWidget(self.splitter_isi_waveform)
        self.mplwidget_isi.setObjectName(_fromUtf8("mplwidget_isi"))
        self.mplwidget_waveform = MatplotlibWidget(self.splitter_isi_waveform)
        self.mplwidget_waveform.setObjectName(_fromUtf8("mplwidget_waveform"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1224, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

from matplotlibwidget import MatplotlibWidget
